# Generated by Django 3.2 on 2021-05-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0006_mascota_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='dueno',
            field=models.CharField(default='--', max_length=45),
        ),
    ]
